apiVersion: apps/v1
kind: Deployment
metadata:
  name: flbook
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: flbook
  template: 
    metadata: 
      labels: 
        app: flbook
        type: backend 
    spec: 
      containers: 
        - name: flbook
          image: sdgadmin/docker-test
          resources: 
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - name: flask-ws-port
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flbook-service
spec:
  selector:
    app: flbook
  type: LoadBalancer
  ports:
  - name: flask-ws-port
    protocol: TCP
    port: 8031
    targetPort: 5000
