FROM nginx:latest
MAINTAINER antuanesco@gmail.com
Run mkdir -p /home/gart/Project
WORKDIR /home/gart/Project
#COPY ./index.html /usr/share/nginx/html/index.htm
#COPY ./nginx.conf /etc/nginx/nginx.conf
#COPY ./nginx.conf /etc/nginx/nginx.conf
#CMD 
