version : '3'

services:
#Nginx Service
  webserver:
    image: antuanesco/webgx:ng-latest
    container_name: webserver
#    links:
#      - mysql
    restart: always
    ports:
      - "8085:80"
    volumes:
      - ./Nginx:/etc/nginx/conf.d
      - ./www:/var/www

  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
