version: '3'

services:
  nginx:
    build: ./Nginx
    ports:
      - "3333:9080"
    volumes:
      - ./Nginx:/etc/nginx/conf.d
      - ./www:/var/www
    network_mode: host

  php:
    build: ./Php
    volumes:
      - ./www:/var/www
    network_mode: host
    image: php:latest

  mysql:
    image: mysql:8
    env_file:
    - mysql/database.env
  mysql:
    build: ./mysql
    restart: always
    network_mode: host
    ports:
      - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
