pipeline {
    environment{
        dockerHubCredentials = "docker-hub-credentials"
        dockerImage1 = ' '
        dockerHubUsername = "oxlamonsrivne"
        dockerImageTag = "1.0.0"
        imageName1 = "$dockerHubUsername/mysql:$dockerImageTag"
        imageName2 = "$dockerHubUsername/nginx:$dockerImageTag"
        imageName3 = "$dockerHubUsername/php:$dockerImageTag"
    }
    agent any
    stages {
        stage('docker-compose up') {
            steps {
                sh 'docker images ls'
                sh 'docker-compose up -d'
            }
        }
        stage('stop running containers') {
            steps {
                sh 'docker images ls'
                sh 'docker-compose stop'
            }
        }
        stage('build images'){
            steps {
                script {
                    sh 'ls -la'
                    //docker.withRegistry('https://hub.docker.com/u/oxlamonsrivne', 'dockerHubCredentials') {
                     //image = docker.image(':bar')
                    // image.pull()
               // sh 'docker tag mysql ${dockerHubUsername}:${dockerImageTag}'
                    dockerImage1 = docker.build(imageName1, 'mysql')
                    dockerImage2 = docker.build(imageName2, 'Nginx')
                    dockerImage3 = docker.build(imageName3, 'Php')
                }
            }

        }
        stage('deploy images'){
            steps{
                script {
                 docker.withRegistry( '', 'dockerHubCredentials') {
                 //sh 'docker push ${dockerHubUsername}/mysql:${dockerImageTag}'
                 dockerImage1.push()
                 dockerImage2.push()
                 dockerImage3.push()
                    }
                }
            }
        }
        stage('remove images'){
            steps{
                sh "docker rmi $imageName1 $imageName2 $imageName3"
           }
        }

    }
}
