apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepik-teachers
spec:
  selector:
    matchLabels:
      app: stepik-teachers
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: stepik-teachers
    spec:
      containers:
      - name: stepik-teachers
        image: juliaolkhovyk/stepik-teachers
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
---

apiVersion: v1
kind: Service
metadata:
  name: stepik-teachers
spec:
  type: NodePort
  selector:
    app: stepik-teachers
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888


